// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIQjA81Ls3ZpiHCb9_YzVO4-vrDNZ-dEE',
    appId: '1:959070768575:web:c008091f1a71223ab3e50a',
    messagingSenderId: '959070768575',
    projectId: 'smart-farm-9c6d7',
    authDomain: 'smart-farm-9c6d7.firebaseapp.com',
    databaseURL: 'https://smart-farm-9c6d7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-9c6d7.firebasestorage.app',
    measurementId: 'G-ZS0MCJW4R5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOSnbafnlJAIoj6yT6j-iwb5V0mJT6yUw',
    appId: '1:959070768575:android:a7c7d1ceef44b3e2b3e50a',
    messagingSenderId: '959070768575',
    projectId: 'smart-farm-9c6d7',
    databaseURL: 'https://smart-farm-9c6d7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-9c6d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpW_S7TJk3xIqeCsj5Oj2bbgBjsmIeuP8',
    appId: '1:959070768575:ios:cdc145a8dba23b52b3e50a',
    messagingSenderId: '959070768575',
    projectId: 'smart-farm-9c6d7',
    databaseURL: 'https://smart-farm-9c6d7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-9c6d7.firebasestorage.app',
    iosBundleId: 'com.example.smartFarm1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpW_S7TJk3xIqeCsj5Oj2bbgBjsmIeuP8',
    appId: '1:959070768575:ios:cdc145a8dba23b52b3e50a',
    messagingSenderId: '959070768575',
    projectId: 'smart-farm-9c6d7',
    databaseURL: 'https://smart-farm-9c6d7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-9c6d7.firebasestorage.app',
    iosBundleId: 'com.example.smartFarm1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIQjA81Ls3ZpiHCb9_YzVO4-vrDNZ-dEE',
    appId: '1:959070768575:web:856100791e62fd79b3e50a',
    messagingSenderId: '959070768575',
    projectId: 'smart-farm-9c6d7',
    authDomain: 'smart-farm-9c6d7.firebaseapp.com',
    databaseURL: 'https://smart-farm-9c6d7-default-rtdb.firebaseio.com',
    storageBucket: 'smart-farm-9c6d7.firebasestorage.app',
    measurementId: 'G-WEL6PVKXV1',
  );
}
